/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuUtama.java
 *
 * Created on Feb 3, 2019, 8:34:21 PM
 */
package posworkshop.tampil;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;




/**
 *
 * @author PERDIANTO
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private DataBarang Barang;
    private Pembelian Beli;
    private BarangMasuk BMasuk;
    private Penjualan Jual;
    private LapDataBarang LapBarang;
    private LapDataPembelian LapBeli;
    private LapDataPenjualan LapJual;
    private LapDataBarangMasuk LapBMasuk;
    
    
    private void setJam(){
        ActionListener listener = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent evt){
                jam.setText(new WaktuSekarang().getWkt());
        }
    };
        new Timer(1000, listener).start();
    }
    private void ResetPusat(){
        try{
            DesktopPane.getSelectedFrame().setClosed(true);
        }catch (Exception e) {}
}

private void PusatBar (javax.swing.plaf.InternalFrameUI jif_f){
((javax.swing.plaf.basic.BasicInternalFrameUI)jif_f).setNorthPane(null);
}

    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setJam();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DesktopPane = new DesktopPaneBackground();
        jLabel1 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 139, 241));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pukul:");

        jam.setText(new WaktuSekarang().getWkt());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal:");

        tgl.setText(new WaktuSekarang().getTgl());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl)
                .addContainerGap(1043, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jam)
                    .addComponent(jLabel3)
                    .addComponent(tgl))
                .addGap(33, 33, 33)
                .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );

        jMenu1.setText("User");

        jMenuItem1.setText("LogOut");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        jMenuItem2.setText("Data Barang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Proses");

        jMenuItem3.setText("Pembelian");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Barang Masuk");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Penjualan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Laporan Data Barang");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Laporan Data Pembelian");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Laporan Data Penjualan");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Laporan Data Barang Masuk");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try{
            ResetPusat();
            if (LapBMasuk==null || LapBMasuk.isClosed()==true){
            LapBMasuk= new LapDataBarangMasuk();
            DesktopPane.add(LapBMasuk);
            }else{
            LapBMasuk.toFront();
            }
            LapBMasuk.setVisible(true);
            LapBMasuk.setSelected(true);
            LapBMasuk.setSize(DesktopPane.getSize());
            PusatBar(LapBMasuk.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            ResetPusat();
            if (Barang==null || Barang.isClosed()==true){
            Barang= new DataBarang();
            DesktopPane.add(Barang);
            }else{
            Barang.toFront();
            }
            Barang.setVisible(true);
            Barang.setSelected(true);
            Barang.setSize(DesktopPane.getSize());
            PusatBar(Barang.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try{
            ResetPusat();
            if (Beli==null || Barang.isClosed()==true){
            Beli= new Pembelian();
            DesktopPane.add(Beli);
            }else{
            Beli.toFront();
            }
            Beli.setVisible(true);
            Beli.setSelected(true);
            Beli.setSize(DesktopPane.getSize());
            PusatBar(Beli.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
            ResetPusat();
            if (BMasuk==null || BMasuk.isClosed()==true){
            BMasuk= new BarangMasuk();
            DesktopPane.add(BMasuk);
            }else{
            BMasuk.toFront();
            }
            BMasuk.setVisible(true);
            BMasuk.setSelected(true);
            BMasuk.setSize(DesktopPane.getSize());
            PusatBar(BMasuk.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         try{
            ResetPusat();
            if (Jual==null || Jual.isClosed()==true){
            Jual= new Penjualan();
            DesktopPane.add(Jual);
            }else{
            Jual.toFront();
            }
            Jual.setVisible(true);
            Jual.setSelected(true);
            Jual.setSize(DesktopPane.getSize());
            PusatBar(Jual.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         try{
            ResetPusat();
            if (LapBarang==null || LapBarang.isClosed()==true){
            LapBarang= new LapDataBarang();
            DesktopPane.add(LapBarang);
            }else{
            Barang.toFront();
            }
            LapBarang.setVisible(true);
            LapBarang.setSelected(true);
            LapBarang.setSize(DesktopPane.getSize());
            PusatBar(LapBarang.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
      
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         try{
            ResetPusat();
            if (LapJual==null || LapJual.isClosed()==true){
            LapJual= new LapDataPenjualan();
            DesktopPane.add(LapJual);
            }else{
            Jual.toFront();
            }
            LapJual.setVisible(true);
            LapJual.setSelected(true);
            LapJual.setSize(DesktopPane.getSize());
            PusatBar(LapJual.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         try{
            ResetPusat();
            if (LapBeli==null || LapBeli.isClosed()==true){
            LapBeli= new LapDataPembelian();
            DesktopPane.add(LapBeli);
            }else{
            Beli.toFront();
            }
            LapBeli.setVisible(true);
            LapBeli.setSelected(true);
            LapBeli.setSize(DesktopPane.getSize());
            PusatBar(LapBeli.getUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Halaman Jabatan !");
        }        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
